plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false

Rails/HasAndBelongsToMany:
  Enabled: false

Layout/LineLength:
  Max: 130

Lint/AmbiguousOperator:
  Exclude:
    - lib/spree_product_labels/engine.rb

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Exclude:
    - app/sidekiq/import_products_job.rb

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Exclude:
    - app/sidekiq/import_products_job.rb

Style/ClassVars:
  Exclude:
    - lib/spree_product_labels/engine.rb

Style/Documentation:
  Enabled: false
